export default () => {
  const wrapForm = document.createElement("div");
  wrapForm.className = "wrap";
  wrapForm.setAttribute("id", "wrapForm");
  const body = document.getElementsByTagName("body");
  const searchForm = document.createElement("div");
  searchForm.className = "search-form";
  searchForm.setAttribute("id", "searchForm");
  wrapForm.append(searchForm);
  const iconSearch = document.createElement("img");
  iconSearch.className = "icon-search";
  iconSearch.setAttribute("src", "../../src/assets/img/iconSearch.png");
  searchForm.append(iconSearch);
  const inputBlock = document.createElement("div");
  inputBlock.className = "input-block";
  searchForm.append(inputBlock);
  const inputWrapper = document.createElement("div");
  inputWrapper.className = "input-wrapper";
  inputWrapper.setAttribute("data-text", "");
  inputWrapper.setAttribute("id", "inputWrapper");
  inputBlock.append(inputWrapper);
  const inputSearch = document.createElement("input");
  inputSearch.setAttribute("type", "text");
  inputSearch.setAttribute("placeholder", "Search movie...");
  inputSearch.setAttribute("required", "");
  inputSearch.setAttribute("minlength", "2");
  inputSearch.setAttribute("maxlength", "50");
  inputSearch.setAttribute("name", "search");
  inputSearch.setAttribute("id", "inputSearch");
  inputSearch.setAttribute("autofocus", "");
  inputSearch.setAttribute("autocomplete", "off");
  inputSearch.className = "input-search"
  inputWrapper.append(inputSearch);
  const iconX = document.createElement("img");
  iconX.className = "icon-x";
  iconX.setAttribute("id", "iconX");
  iconX.setAttribute("src", "../../src/assets/img/x-icon.png");
  inputBlock.append(iconX);
  const iconKeyboard = document.createElement("img");
  iconKeyboard.className = "icon-keyboard";
  iconKeyboard.setAttribute("src", "../../src/assets/img/iconKeyboard.png");
  iconKeyboard.setAttribute("id", "iconKeyboard");
  searchForm.append(iconKeyboard);
  const buttonSearch = document.createElement("button");
  buttonSearch.className = "button-search";
  buttonSearch.setAttribute("id", "buttonSearch");
  buttonSearch.textContent = "search";
  searchForm.append(buttonSearch);
  const messageBlock = document.createElement("div");
  messageBlock.className = "message-block";
  messageBlock.setAttribute("id", "messageBlock");
  const message = document.createElement("p");
  message.className = "message";
  message.textContent = "No results for \"Something went wrong\"";
  messageBlock.append(message);
  wrapForm.append(messageBlock);
  body[0].append(wrapForm);
  const loadWrap = document.createElement("div");
  loadWrap.className = "load-wrap";
  loadWrap.setAttribute("id", "loadWrap");
  const load = document.createElement("div");
  load.className = "load";
  loadWrap.append(load);
  const textLoad = document.createElement("p");
  textLoad.textContent = "Loading...";
  load.append(textLoad);
  const spinner = document.createElement("div");
  spinner.className = "spinner";

  const bubble1 = document.createElement("div");
  bubble1.className = "bubble-1";
  spinner.append(bubble1);
  const bubble2 = document.createElement("div");
  bubble2.className = "bubble-2";
  spinner.append(bubble2);
  load.append(spinner);
  searchForm.append(loadWrap);

  inputSearch.addEventListener("keyup", event => {
    inputWrapper.setAttribute("data-text", event.target.value);
  });
  iconX.addEventListener("click", () => {
    inputWrapper.setAttribute("data-text", "");
  });
  buttonSearch.addEventListener("click", () => {
    buttonSearch.style.display = "none";
    loadWrap.style.display = "block";
  });
};